### Ping - Endpoint for test
GET http://localhost:3003/ping

### User registration - Endpoint for user registration
POST http://localhost:3003/users
Content-Type: application/json

{
    "email": "mcdonalts@gmail.com",
    "password": "burguerKing"
}

### Get all users
GET http://localhost:3003/users

### Product registration - Endpoint for product registration
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Fanta uva",
    "price": 5.90
}

### Get all products
GET http://localhost:3003/products

### Register purchases
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id": "1",
    "product_id": "3",
    "quantity": 2
}

### Get purchase by user
GET http://localhost:3003/users/1/purchase
